* Updated init script

diff --git a/debian/psad.init b/debian/psad.init
--- a/debian/psad.init
+++ b/debian/psad.init
@@ -58,6 +58,25 @@ check_config()
 }
 
 #
+# Function to check if psad is running
+#
+#    0 : the psad.pid file has been found ; we assume the daemon is running
+#    1 : no pid file has been found ; we assume the daemon is not running
+#
+is_psad_running()
+{
+        local pidfile="$PIDDIR/psad.pid"
+        local retval
+
+        retval=0
+        if [ -r "$pidfile" ]; then
+                retval=1
+        fi
+
+        return $retval
+}
+
+#
 # Function that starts the daemon/service
 #
 #   0 : daemon has been started or was already running
@@ -68,17 +87,21 @@ do_start()
 {
 	local retval
 
-    echo -n "Starting $DESC: $NAME "
 
-    mkdir -p $PIDDIR
-    chmod 755 $PIDDIR
+        mkdir -p $PIDDIR
+        chmod 755 $PIDDIR
 
 	# Check psad configuration
 	check_config
 	retval=$?
 
 	# Try to start psad
-	if [ "$retval"  = "0" ]; then
+        is_psad_running
+        if [ "$?" = 1 ]; then
+            log_action_msg "The psad daemon is already running"
+            retval=0
+
+	elif [ "$retval"  = "0" ]; then
 		start-stop-daemon --start --quiet --pidfile $PIDDIR/$NAME --exec $DAEMON -- $DAEMON_ARGS
 		retval="$?"
 	fi
@@ -86,19 +109,21 @@ do_start()
 	# Handle return status codes
 	case "$retval" in
 		0)	 
-			log_success_msg
 			;;
 		6)	
-			log_failure_msg "You are missing the configuration file $ConfFile."
+			log_action_msg "You are missing the configuration file $ConfFile" || true
 			;;
 		9)	
 			retval=0
 			;;
 		*)
 			retval=1
-			log_failure_msg "Unable to start the daemon."
+			log_action_msg "Unable to start the daemon" || true
 			;;
 	esac
+
+	log_daemon_msg "Starting Port Scan Attack Detector" "psad" || true
+        log_end_msg $retval || true
 
 	return $retval
 }
@@ -122,8 +147,6 @@ do_stop()
 	local pid pidfile
 	local process_list="psadwatchd kmsgsd psad"
 
-	echo -n "Stopping $DESC:"
-
 	# For each process
 	for process in $process_list; do
 
@@ -131,7 +154,7 @@ do_stop()
 		status="0"
 		kill_status="1"
 
-		echo -n " $process"
+		log_action_msg "Stopping the $process process"
 
 		# Try to kill the process associated to the pid
 		if [ -r "$pidfile" ]; then
@@ -156,13 +179,12 @@ do_stop()
 
 	done
 
-
-	if [ "$retval" = "0" ]; then
-		log_success_msg
-	else
-		echo -n " "
-		log_failure_msg "One or more process could not be stopped."
+	if [ "$retval" != "0" ]; then
+		log_action_msg "One or more process could not be stopped" || true
 	fi
+
+        log_daemon_msg "Stopping Port Scan Attack Detector" "psad" || true
+        log_end_msg $retval || true
 
 	return $retval
 }
